# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d427583d34ec0ffe44327af21797404b459685fd9603034bf4c7e47e447874c1c4d19cc89e5e0efd0b9a113da3dc45f3518484f5eb10901bdf4235d3e10eaada

test:
  secret_key_base: 82b2e6faa2d48615d76b5cd8e38ec2806efcb48bcec9668c67f3298d76a37d3ed318e72c3d3a27dbcd5ab6c0a51f880e63375642bda1dfd62de37ccb9c84aa0f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
